version: '2.3'

services:

  cut:
    image: cut
    container_name: cut
    working_dir: /cut
    build:
      context: ../
      dockerfile: docker/Dockerfile.cut
    volumes:
      - ../:/cut
      - /your-folder-path/polyp-data/:/polyp-data:ro
      - /your-folder-path/synth-colon/:/synth-colon:ro
    runtime: nvidia
    shm_size: '12gb'
    command: tail /dev/null -f
  
  blender:
    image: blender
    container_name: blender
    working_dir: /blender
    build:
      context: ../
      dockerfile: docker/Dockerfile.blender
    volumes:
      - ../:/blender
      - /your-folder-path/polyp-data/:/polyp-data:ro
    command: tail /dev/null -f
